{
 "title": "Tankapplication",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Levels and Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "GDB_signals_tankSignals_actLevel",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "GDB_signals_bottleSignals_actLevel",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "GDB_signals_tankSignals_actTemperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Faulty Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "GDB_process_numberFaulty",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Produced Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "GDB_process_numberProduced",
     "query": "SELECT \"value\" FROM \"GDB_process_numberFaulty\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}